In [1]:
using JLD,JLD2,Knet
using Base.Iterators: flatten
using Random, Distributions

In [2]:
include("types.jl")
include("pre_processing.jl")
include("encoder_utils.jl")

fillvecs! (generic function with 1 method)

In [46]:
d = JLD.load("english_chmodel2.jld2")
v = create_vocab(d["new_d"])
corpus = load_conllu("tr_imst-ud-train.conllu",v)
wmodel = makewmodel(d["new_d"])

9-element Array{Array{Float32,2},1}:
 [0.593419 0.190279 … 0.11003 -0.000173569; -0.236287 0.455614 … 0.138825 -0.0971059; … ; -0.341316 0.0835031 … -0.0285478 -0.0718531; -0.205958 -0.168918 … -0.13226 -0.0319474]
 [0.0708071 -0.456333 … 0.557484 0.094816; -1.61625 -1.37924 … 0.342474 0.548784; … ; 1.07664 -0.430524 … -0.360356 0.668587; 0.324491 -0.175173 … -0.790751 1.16417]            
 [1.2185; 1.52402; … ; -1.1745; -1.53404]                                                                                                                                        
 [1.47578 0.055072 … -0.2823 -1.58338; -1.95253 -0.402249 … -0.221281 -0.667834; … ; 1.28302 -0.0459206 … -2.12551 -0.95058; 0.924036 0.269601 … 0.515548 7.38111]               
 [-0.916012; -2.25621; … ; -0.166855; 0.169325]                                                                                                                                  
 [1.70814 0.787587 … -0.636378 -1.76298; 4.32346 5.14362 … 0.705938 -0.04

In [47]:
d["new_d"]

Dict{String,Any} with 13 entries:
  "back"       => Any[Float32[1.70814 0.787587 … -0.636378 -1.76298; 4.32346 5.…
  "word_vocab" => Dict("null"=>8668,"Secure"=>7932,"Puppy"=>9040,"progression"=…
  "char_vocab" => Dict('\x00\x00\x00\x42'=>37,'\x00\x00\x20\x1d'=>116,'\x00\x00…
  "eowchar"    => '\x00\x00\x00\x13'
  "sowchar"    => '\x00\x00\x00\x12'
  "forw"       => Any[Float32[1.47578 0.055072 … -0.2823 -1.58338; -1.95253 -0.…
  "eosword"    => "</s>"
  "sosword"    => "<s>"
  "soft"       => Array{Float32,2}[[-0.303084 -1.18525 … -0.281071 -0.2053; -0.…
  "unkword"    => "<unk>"
  "cembed"     => Float32[0.593419 0.190279 … 0.11003 -0.000173569; -0.236287 0…
  "char"       => Any[Float32[0.0708071 -0.456333 … 0.557484 0.094816; -1.61625…
  "unkchar"    => '\x00\x00\x00\x11'

In [48]:
s = corpus[1]

Sanal parçacıklar sa bunların hiçbirini yapamazlar . 

In [49]:
fillvecs!(wmodel, corpus, v)

┌ Warning: `getval` is deprecated, use `value` instead.
│   caller = #lmloss#18(::Array{Float64,1}, ::Function, ::Array{Array{Float32,2},1}, ::Array{Array{Int64,1},1}, ::Array{Array{Float32,1},1}, ::Array{Any,1}, ::Array{Any,1}) at encoder_utils.jl:59
└ @ Main /home/caltan14/gbdp/encoder_utils.jl:59


In [50]:
ev = extend_vocab!(v, corpus)

ExtendedVocab(Dict("Abr"=>26,"PCNom"=>18,"Dup"=>27,"PCIns"=>30,"Since"=>32,"Postp"=>31,"Interj"=>24,"Ques"=>14,"Demons"=>5,"NAdj"=>11…), Dict("VerbForm=Vnoun"=>43,"Person=3"=>4,"Case=Acc"=>11,"Number=Sing"=>7,"Mood=Nec"=>54,"Aspect=Prog"=>27,"Person[psor]=3"=>13,"VerbForm=Conv"=>44,"Aspect=Hab"=>15,"Voice=CauPass"=>46…), Vocab(Dict('\x00\x00\x00\x42'=>37,'\x00\x00\x20\x1d'=>116,'\x00\x00\x00\x58'=>87,'\x00\x00\x20\x44'=>110,'\x00\x00\x00\x56'=>59,'\x00\x00\x00\xd7'=>107,'\x00\x00\x00\x48'=>29,'\x00\x00\x00\x75'=>5,'\x00\x00\x00\x50'=>11,'\x00\x00\x00\x7a'=>61…), Dict("çıkaramayacaklarını"=>7805,"apartmanın"=>13565,"Güreş"=>2733,"karıştı"=>1790,"ikibin'de"=>7225,"formülü"=>4676,"ANAP'ı"=>4506,"ihmal"=>5116,"Virgülden"=>9483,"il"=>6725…), Dict("null"=>8668,"Secure"=>7932,"Puppy"=>9040,"progression"=>11757,"gathered"=>6954,"Core"=>3600,"lovers"=>8832,"underground"=>9093,"backup"=>5047,"caught"=>2501…), "<s>", "</s>", "<unk>", '\x00\x00\x00\x12', '\x00\x00\x00\x13', '\x00\x00\x00\x11', Dic

In [51]:
mutable struct FeatureSource
    postags::Array{Float64}
    xpostags::Array{Float64}
    feats::Array{Float64}
end

In [52]:
Random.seed!(5)

MersenneTwister(UInt32[0x00000005], Random.DSFMT.DSFMT_state(Int32[-85655800, 1072952617, -522203688, 1073721902, 1588056292, 1072823262, 1930843968, 1073164255, -719121749, 1073022455  …  647343590, 1073165527, 1405924594, 1072769931, 1969171087, 42945320, -226019479, -1469955508, 382, 0]), [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], UInt128[0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000  …  0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x0000000000000

In [53]:
# Size of the randomly initialized column vectors that represents features such that xpostag, upostag, feats
tagrepsize = 32

32

In [54]:
function createcolvecs(corpus,ev)
    dist = Normal()
    xpostags = rand(dist, (tagrepsize, length(keys(ev.xpostags))))
    postags = rand(dist, (tagrepsize, length(keys(ev.vocab.postags))))
    feats = rand(dist, (tagrepsize, length(keys(ev.feats))))
    return FeatureSource(postags,xpostags,feats)
end

createcolvecs (generic function with 1 method)

In [55]:
fs = createcolvecs(corpus,ev)

FeatureSource([-0.542853 -0.992666 … 1.6983 -2.17757; 0.584793 1.14789 … 0.609551 -2.53964; … ; -0.825722 -2.10416 … 1.05649 -0.0918268; -2.90343 -0.18003 … -0.493267 1.06719], [1.46431 -0.123083 … 0.537261 0.982212; 0.260871 0.318797 … 0.798075 0.462872; … ; 1.29726 0.789473 … -0.589126 0.00480883; -1.61916 1.94446 … -1.57499 -1.55228], [0.819346 0.699932 … -0.915596 -1.791; 0.504342 -2.51908 … -0.0451559 0.201541; … ; 0.493422 0.875163 … -0.962536 1.63154; 0.395833 0.817469 … -1.82224 0.441632])

In [56]:
fs.xpostags[:,s.xpostag[1]]

32-element Array{Float64,1}:
 -0.12308284078752839 
  0.3187970252733201  
 -0.7910831402314742  
  0.4421427803274385  
 -1.0104910883715064  
  0.4859593864808637  
  0.07200507807828677 
 -1.2444991825818057  
  0.7321681826266581  
 -1.1034372169774     
  1.9233445877702353  
  1.3775612444949075  
 -1.867527226614093   
  ⋮                   
 -0.050779830784901565
 -0.7361552384181024  
 -0.9948592466621384  
 -0.27768412415298127 
 -0.4450002990337082  
  0.9776749351851451  
 -0.7948204573786628  
  0.8486637089024585  
 -1.4446783561804906  
 -0.6733567529686127  
  0.7894731805379925  
  1.9444589221380262  

In [57]:
function sumfeats(feats, fs)
    sum = zeros(length(fs.feats[:,1]))
    for i in 1:length(feats)
        sum .+= fs.feats[:,feats[i]]
    end
    return sum
end

sumfeats (generic function with 1 method)

In [58]:
function createfeatvec!(corpus, fs)
    for sent in corpus
        for i in 1:length(sent)
            push!(sent.cavec, vcat(sent.wvec[i], sent.fvec[i], sent.bvec[i], fs.postags[:,sent.postag[i]], fs.xpostags[:,sent.xpostag[i]], sumfeats(sent.feats[i],fs)))
        end
    end
end

createfeatvec! (generic function with 1 method)

In [59]:
s.cavec

0-element Array{Any,1}

In [60]:
createfeatvec!(corpus, fs)

In [61]:
s.cavec[2][951:982]

32-element Array{Float64,1}:
 -0.1311150143919328  
 -1.677971571112714   
 -1.2598708654940836  
  0.37398323197209205 
  0.7517536501770229  
  1.0319548655085806  
  0.30156213535618165 
 -0.7764951705395398  
 -0.3284245341477391  
 -1.995153243063271   
  1.1956060383577813  
 -0.773249822675974   
  1.3211269528055156  
  ⋮                   
 -0.8533704218618776  
 -1.1505363442394707  
  0.9761759177025612  
 -1.171026399033072   
  1.793692224176808   
 -0.546172172962383   
 -0.37601361704464076 
  1.6577882662957313  
  0.016430384331410506
 -0.68076827209089    
 -1.7906290138997918  
  1.2019453653596417  

In [62]:
s.postag

7-element Array{UInt8,1}:
 0x01
 0x08
 0x04
 0x0b
 0x0b
 0x10
 0x0d

In [63]:
words, sents, maxwordlen, maxsentlen = maptoint(corpus, v)

(Array{Int64,1}[[1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1], [1, 1, 1]  …  [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]], Array{Int64,1}[[3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 9], [14, 15, 16, 17, 18, 19, 15, 20, 21, 22, 23, 24, 25, 26, 9], [27, 28, 9], [29, 30, 31, 9], [32, 33, 34, 9], [35, 36, 37, 9], [38, 39], [40, 41, 9], [42, 43, 44, 9]  …  [13779, 13780, 1124, 73, 13781, 13782, 9633, 9], [13783, 13784, 15, 13785, 13786, 13787, 606, 607, 99, 39], [13788, 9628, 1915, 215, 9], [13789, 15, 854, 658, 4761, 13790, 9], [13791, 13792, 9], [5308, 13793, 6209, 146, 9], [8698, 5901, 160, 13794, 7669, 3910, 13795, 15, 13796, 13797, 1161, 941, 13

In [64]:
words

13808-element Array{Array{Int64,1},1}:
 [1, 1, 1]                        
 [1, 1, 1, 1]                     
 [1, 1, 1, 1, 1]                  
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [1, 1]                           
 [1, 1, 1, 1, 1, 1, 1, 1]         
 [1, 1, 1, 1, 1, 1, 1, 1, 1]      
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]   
 [1]                              
 [1, 1, 1]                        
 [1, 1, 1]                        
 [1, 1, 1, 1, 1, 1]               
 [1, 1, 1, 1, 1, 1]               
 ⋮                                
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [1, 1, 1, 1, 1, 1, 1, 1]         
 [1, 1, 1, 1, 1, 1]               
 [1, 1, 1, 1, 1, 1, 1, 1]         
 [1, 1, 1, 1, 1, 1, 1]            
 [1, 1, 1, 1, 1, 1, 1, 1]         
 [1, 1, 1, 1, 1, 1, 1, 1]         
 [1, 1, 1, 1, 1, 1, 1, 1]         
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [1, 1, 1, 1, 1, 1, 1, 1, 1]      
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 [1, 1, 1, 1, 1, 1]               

In [65]:
sents

3685-element Array{Array{Int64,1},1}:
 [3, 4, 5, 6, 7, 8, 9]                                                                                            
 [10, 11, 12, 13, 9]                                                                                              
 [14, 15, 16, 17, 18, 19, 15, 20, 21, 22, 23, 24, 25, 26, 9]                                                      
 [27, 28, 9]                                                                                                      
 [29, 30, 31, 9]                                                                                                  
 [32, 33, 34, 9]                                                                                                  
 [35, 36, 37, 9]                                                                                                  
 [38, 39]                                                                                                         
 [40, 41, 9]                              

In [66]:
count = 0
unq = []
for s in corpus
   for w in s.word
        if !(w in unq)
           push!(unq, w) 
        end
    end
end

In [67]:
unq

13806-element Array{Any,1}:
 "Sanal"      
 "parçacıklar"
 "sa"         
 "bunların"   
 "hiçbirini"  
 "yapamazlar" 
 "."          
 "Ona"        
 "her"        
 "şeyimi"     
 "verdim"     
 "Karşısında" 
 ","          
 ⋮            
 "imalatından"
 "olmuşlar"   
 "Geçici"     
 "tasarısı"   
 "sunuldu"    
 "peynirin"   
 "efsanesi"   
 "başbakan"   
 "düzenlemede"
 "getirecek"  
 "yetmişsekiz"
 "mesajı"     

In [68]:
v.unkchar

'\x00\x00\x00\x11': Malformed UTF-8 (category Ma: Malformed, bad data)

In [69]:
v.cdict[v.unkchar]

1

In [70]:
v.idict

Dict{String,Int64} with 13808 entries:
  "çıkaramayacaklarını" => 7805
  "apartmanın"          => 13565
  "Güreş"               => 2733
  "karıştı"             => 1790
  "ikibin'de"           => 7225
  "formülü"             => 4676
  "ANAP'ı"              => 4506
  "ihmal"               => 5116
  "Virgülden"           => 9483
  "il"                  => 6725
  "devrimlerle"         => 11077
  "Kıyı"                => 11182
  "azla"                => 8931
  "Duvarlarla"          => 4778
  "tı"                  => 1253
  "bağlamasını"         => 10389
  "geçme"               => 13795
  "geceye"              => 6674
  "böyle"               => 613
  "yasaklamanın"        => 422
  "anlayışıyla"         => 8282
  "yaklaştığını"        => 12469
  "bakınır"             => 9900
  "buruşturdu"          => 9728
  "eritme"              => 8462
  ⋮                     => ⋮

In [71]:
aaa = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [72]:
don = empty!(aaa)

0-element Array{Int64,1}

In [73]:
don

0-element Array{Int64,1}

In [74]:
v.cdict

Dict{Char,Int64} with 122 entries:
  '\x00\x00\x00\x42' => 37
  '\x00\x00\x20\x1d' => 116
  '\x00\x00\x00\x58' => 87
  '\x00\x00\x20\x44' => 110
  '\x00\x00\x00\x56' => 59
  '\x00\x00\x00\xd7' => 107
  '\x00\x00\x00\x48' => 29
  '\x00\x00\x00\x75' => 5
  '\x00\x00\x00\x50' => 11
  '\x00\x00\x00\x7a' => 61
  '\x00\x00\x00\x63' => 9
  '\x00\x00\x00\x3b' => 93
  '\x00\x00\x00\x7c' => 85
  '\x00\x00\x00\x4a' => 60
  '\x00\x00\x00\x21' => 83
  '\x00\x00\x00\x6c' => 6
  '\x00\x00\x00\x70' => 12
  '\x00\x00\x00\xae' => 80
  '\x00\x00\x00\x27' => 84
  '\x00\x00\x00\x23' => 98
  '\x00\x00\x00\x3d' => 71
  '\x00\x00\xd0\xa5' => 122
  '\x00\x00\x00\x2d' => 62
  '\x00\x00\x00\x79' => 13
  '\x00\x00\x00\x69' => 17
  ⋮                  => ⋮

In [75]:
Char(0xa5)

'¥': Unicode U+00a5 (category Sc: Symbol, currency)

In [76]:
v.cdict[v.sowchar]

2

In [77]:
malformed = '\x00\x00\x00\x2d'

LoadError: syntax: invalid character literal

In [78]:
for w in (v.sosword, v.eosword)
    println(w)
end

<s>
</s>


In [79]:
w = v.sosword

"<s>"

In [80]:
for c in w
  println(c)  
end

<
s
>


In [81]:
v.cdict

Dict{Char,Int64} with 122 entries:
  '\x00\x00\x00\x42' => 37
  '\x00\x00\x20\x1d' => 116
  '\x00\x00\x00\x58' => 87
  '\x00\x00\x20\x44' => 110
  '\x00\x00\x00\x56' => 59
  '\x00\x00\x00\xd7' => 107
  '\x00\x00\x00\x48' => 29
  '\x00\x00\x00\x75' => 5
  '\x00\x00\x00\x50' => 11
  '\x00\x00\x00\x7a' => 61
  '\x00\x00\x00\x63' => 9
  '\x00\x00\x00\x3b' => 93
  '\x00\x00\x00\x7c' => 85
  '\x00\x00\x00\x4a' => 60
  '\x00\x00\x00\x21' => 83
  '\x00\x00\x00\x6c' => 6
  '\x00\x00\x00\x70' => 12
  '\x00\x00\x00\xae' => 80
  '\x00\x00\x00\x27' => 84
  '\x00\x00\x00\x23' => 98
  '\x00\x00\x00\x3d' => 71
  '\x00\x00\xd0\xa5' => 122
  '\x00\x00\x00\x2d' => 62
  '\x00\x00\x00\x79' => 13
  '\x00\x00\x00\x69' => 17
  ⋮                  => ⋮

In [82]:
get(v.cdict, '\x00\x00\x00\x42', 1)

LoadError: syntax: invalid character literal

In [83]:
typeof('\x00\x00\x00\x42')

LoadError: syntax: invalid character literal

In [84]:
v.cdict

Dict{Char,Int64} with 122 entries:
  '\x00\x00\x00\x42' => 37
  '\x00\x00\x20\x1d' => 116
  '\x00\x00\x00\x58' => 87
  '\x00\x00\x20\x44' => 110
  '\x00\x00\x00\x56' => 59
  '\x00\x00\x00\xd7' => 107
  '\x00\x00\x00\x48' => 29
  '\x00\x00\x00\x75' => 5
  '\x00\x00\x00\x50' => 11
  '\x00\x00\x00\x7a' => 61
  '\x00\x00\x00\x63' => 9
  '\x00\x00\x00\x3b' => 93
  '\x00\x00\x00\x7c' => 85
  '\x00\x00\x00\x4a' => 60
  '\x00\x00\x00\x21' => 83
  '\x00\x00\x00\x6c' => 6
  '\x00\x00\x00\x70' => 12
  '\x00\x00\x00\xae' => 80
  '\x00\x00\x00\x27' => 84
  '\x00\x00\x00\x23' => 98
  '\x00\x00\x00\x3d' => 71
  '\x00\x00\xd0\xa5' => 122
  '\x00\x00\x00\x2d' => 62
  '\x00\x00\x00\x79' => 13
  '\x00\x00\x00\x69' => 17
  ⋮                  => ⋮

KeyError: KeyError: key "char_vocab" not found