In [1]:
using JLD,JLD2,Knet
using Base.Iterators: flatten
using Random, Distributions
Random.seed!(5)

MersenneTwister(UInt32[0x00000005], Random.DSFMT.DSFMT_state(Int32[-85655800, 1072952617, -522203688, 1073721902, 1588056292, 1072823262, 1930843968, 1073164255, -719121749, 1073022455  …  647343590, 1073165527, 1405924594, 1072769931, 1969171087, 42945320, -226019479, -1469955508, 382, 0]), [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], UInt128[0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000  …  0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x0000000000000

In [2]:
include("types.jl")
include("pre_processing.jl")
include("encoder_utils.jl")

mywordlstm (generic function with 1 method)

In [3]:
d = JLD.load("english_chmodel3.jld2")
d["new_d2"]["unkchar"] = Char(0x11)
d["new_d2"]["sowchar"] = Char(0x12)
d["new_d2"]["eowchar"] = Char(0x13)

'\x13': ASCII/Unicode U+0013 (category Cc: Other, control)

In [4]:
v = create_vocab(d["new_d2"])
corpus = load_conllu("tr_imst-ud-train.conllu",v)
wmodel = makewmodel(d["new_d2"])

9-element Array{Array{Float32,2},1}:
 [0.593419 0.190279 … 0.11003 -0.000173569; -0.236287 0.455614 … 0.138825 -0.0971059; … ; -0.341316 0.0835031 … -0.0285478 -0.0718531; -0.205958 -0.168918 … -0.13226 -0.0319474]
 [0.0708071 -0.456333 … 0.557484 0.094816; -1.61625 -1.37924 … 0.342474 0.548784; … ; 1.07664 -0.430524 … -0.360356 0.668587; 0.324491 -0.175173 … -0.790751 1.16417]            
 [1.2185; 1.52402; … ; -1.1745; -1.53404]                                                                                                                                        
 [1.47578 0.055072 … -0.2823 -1.58338; -1.95253 -0.402249 … -0.221281 -0.667834; … ; 1.28302 -0.0459206 … -2.12551 -0.95058; 0.924036 0.269601 … 0.515548 7.38111]               
 [-0.916012; -2.25621; … ; -0.166855; 0.169325]                                                                                                                                  
 [1.70814 0.787587 … -0.636378 -1.76298; 4.32346 5.14362 … 0.705938 -0.04

In [5]:
s = corpus[1]

Sanal parçacıklar sa bunların hiçbirini yapamazlar . 

In [6]:
ev = extend_vocab!(v, corpus)
fs = createcolvecs(corpus,ev)

FeatureSource([-0.542853 -0.992666 … 1.6983 -2.17757; 0.584793 1.14789 … 0.609551 -2.53964; … ; -0.825722 -2.10416 … 1.05649 -0.0918268; -2.90343 -0.18003 … -0.493267 1.06719], [1.46431 -0.123083 … 0.537261 0.982212; 0.260871 0.318797 … 0.798075 0.462872; … ; 1.29726 0.789473 … -0.589126 0.00480883; -1.61916 1.94446 … -1.57499 -1.55228], [0.819346 0.699932 … -0.915596 -1.791; 0.504342 -2.51908 … -0.0451559 0.201541; … ; 0.493422 0.875163 … -0.962536 1.63154; 0.395833 0.817469 … -1.82224 0.441632])

In [7]:
fillvecs!(wmodel, corpus, v, fs)

┌ Warning: `getval` is deprecated, use `value` instead.
│   caller = #lmloss#18(::Array{Float64,1}, ::Function, ::Array{Array{Float32,2},1}, ::Array{Array{Int64,1},1}, ::Array{Array{Float32,1},1}, ::Array{Any,1}, ::Array{Any,1}) at encoder_utils.jl:63
└ @ Main /home/caltan14/gbdp/encoder_utils.jl:63


In [9]:
fillcavec!(corpus)

In [11]:
bitches = minibatch(corpus, 32; shuf=true)

116-element Array{Any,1}:
 Any[Aklığından ötürü alır bu adı . , Arat , Teknisyen Yüzbaşı N . , Bunun da temelinde insan var . , Yani ... günah çıkaralım işte . , Zenginleri seven , yoksulları döven . , Şostakoviç 'miş ! Tövbe yarabbi . , Birinci Erim Hükümeti ydi bu . , Şimdi adımlarını daha da hızlandırmıştı . , Bütün sınıfın kızlarının gözü Tibet'te . , Kendilerine aşırı güven li ler .   …  Bak şimdi birdenbire aklıma geldi . , Zaman geçtikçe anasını özlemeye başlamıştı . , Korku içinde ölmek zorunda sın . , Zaten kendileri duygularını tanımadıklarını söylüyorlar . , Sen beni şaşırtıyorsun , dedi . , - Evet , meslektaş sayılırız . , Toz lu ve solgun dular . , O parktan kurtulana pek rastlamadım . , Annesi bizi içeriye davet etti . , Aşık olduğum için utanıyorum sanıyorum . ]                                                                                                                                                                                                                     

In [151]:
# Create input matrix
relmatrix = createrelmatrix(s)

1900×49 Array{Float64,2}:
 -7.41368e-37  -7.41368e-37  -7.41368e-37  …   0.764993      0.764993    
 -1.73598e-8   -1.73598e-8   -1.73598e-8       9.42391e-10   9.42391e-10 
  0.00176632    0.00176632    0.00176632       0.00138876    0.00138876  
  1.13315e-17   1.13315e-17   1.13315e-17     -4.5141e-10   -4.5141e-10  
 -4.05576e-10  -4.05576e-10  -4.05576e-10      1.47003e-6    1.47003e-6  
 -1.27773e-6   -1.27773e-6   -1.27773e-6   …   0.761234      0.761234    
  0.999986      0.999986      0.999986         2.28466e-19   2.28466e-19 
  0.992126      0.992126      0.992126        -0.000163521  -0.000163521 
 -8.91425e-13  -8.91425e-13  -8.91425e-13      0.952176      0.952176    
  3.66729e-6    3.66729e-6    3.66729e-6      -6.96898e-9   -6.96898e-9  
  4.42818e-11   4.42818e-11   4.42818e-11  …  -0.761648     -0.761648    
  0.937807      0.937807      0.937807        -0.00152425   -0.00152425  
 -3.11616e-9   -3.11616e-9   -3.11616e-9       8.32028e-7    8.32028e-7  
  ⋮         

In [160]:
# Initialize model weights
dist = Normal()
weights = rand(dist, (1,length(corpus[1].cavec[1]) * 2)) # dimension is (1,1900)
weights = hcat(weights,0)

1×1901 Array{Float64,2}:
 0.112474  -0.831161  2.24681  …  0.426758  -0.122993  0.817235  0.0

In [153]:
function non_lin(w,x)
   return transpose(w[1:length(w)-1])*x .+ w[length(w)] 
end

non_lin (generic function with 1 method)

In [154]:
ygold = createygold(s) # No need to represent 0s, 1s

1×49 LinearAlgebra.Transpose{Any,Array{Any,1}}:
 0  1  0  0  0  0  0  0  0  0  0  0  1  …  0  0  0  0  0  0  0  0  0  0  1  0

In [161]:
ypred = non_lin(weights, relmatrix)

1×49 Array{Float64,2}:
 2.1942  19.4418  19.2863  18.7448  5.04162  …  -2.63576  -0.950057  10.9051

In [162]:
Knet.nll(reshape(ypred, (7,7)), s.head) # dims=1 default means predictions are column vectors, avg=true default

8.65053400727543

In [163]:
accuracy(reshape(ypred, (7,7)), s.head)

0.2857142857142857

In [86]:
total_ypreds = predict(bitches, weights)

116-element Array{Any,1}:
 Any[[-5.66771 4.99843 … 9.58134 6.3163], [-2.08317 3.39674 … 17.3805 18.7313], [3.30966 12.97 … 22.4688 10.441], [-1.98299 -1.54925 … 34.0065 24.9093], [-17.6575 1.15928 … 28.7703 11.2779], [-19.9883 -20.4413 … 25.2282 12.5396], [-0.938437 -8.70115 … 13.4037 11.7089], [-9.97796 -12.6766 … 23.2351 5.14861], [-21.9523 -1.62994 … 16.1199 13.3102], [-1.80099 18.7299 … 30.0781 20.2974]  …  [5.76427 21.7566 … 40.837 18.0269], [-11.6479 24.7778 … 36.5821 17.7602], [2.74686 12.4674 … 24.758 18.9485], [-9.93631 -3.23575 … 30.5553 13.567], [-9.85352 7.68763 … 22.952 14.1622], [-30.9136 -5.24109 … 28.9229 11.4361], [-0.548321 6.26774 … 42.7989 13.7908], [-17.2469 11.0068 … 35.8498 17.2577], [-1.45351 18.3501 … 41.9606 14.9396], [-7.20275 9.52547 … 31.0206 12.3759]]     
 Any[[-19.1793 -7.93702 … 23.8384 8.83778], [6.24716 23.1295 … 33.0566 13.9117], [-6.94666 -12.8245 … 21.5941 13.6658], [-15.416 -1.67916 … 19.9066 10.8174], [-9.15503 7.94676 … 29.9886 6.90492], [-12.92

In [84]:
total_ygold = collectygold(bitches)

116-element Array{Any,1}:
 Any[Int16[3, 1, 0, 5, 3, 3], Int16[0, 5, 4, 5, 1, 5], Int16[3, 1, 5, 5, 0, 5], Int16[0, 3, 1, 3, 3, 1], Int16[2, 5, 2, 5, 0, 5], Int16[0, 1, 1, 1, 4, 5], Int16[2, 0, 2, 2, 2, 2], Int16[5, 5, 5, 3, 0, 5], Int16[2, 3, 4, 5, 0, 5], Int16[3, 3, 0, 3, 3, 3]  …  Int16[0, 4, 4, 1, 4, 4], Int16[2, 5, 4, 5, 0, 5], Int16[2, 3, 4, 0, 4, 4], Int16[0, 5, 4, 5, 1, 5], Int16[3, 3, 5, 3, 0, 5], Int16[0, 1, 5, 5, 1, 5], Int16[4, 1, 4, 0, 4, 4], Int16[2, 3, 5, 5, 0, 5], Int16[4, 4, 4, 0, 4, 4], Int16[4, 1, 1, 5, 0, 5]]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

In [ ]:
# Going into autograd

In [138]:
# Compute loss using gradient
J = @diff Knet.nll(reshape(ypred, (7,7)), s.head) 

T(6.036426920501731)

In [134]:
Knet.params(J) |> collect

1-element Array{Param{Array{Float64,2}},1}:
 P(Array{Float64,2}(1,49))

In [135]:
gradw = grad(J, Param(pweights[1:length(pweights)-1]))

In [142]:
struct Linear; w; b; end
(m::Linear)(x) = m.w * x .+ m.b
(m::Linear)(x, y) = Knet.nll(m(x), y)
#(m::Linear)(data::Data) = mean(m(x,y) for (x,y) in data)
Linear(i::Int,o::Int,scale=0.01) = Linear(Param(scale * randn(o,i)), Param(zeros(o)))

Linear

In [146]:
model = Linear(length(corpus[1].cavec[1]) * 2, 1)

Linear(P(Array{Float64,2}(1,1900)), P(Array{Float64,1}(1)))

In [147]:
model.w

1×1900 Param{Array{Float64,2}}:
 0.0161268  -0.0106522  0.0171532  0.00393771  …  0.00575107  -0.000616583

In [148]:
model.b

1-element Param{Array{Float64,1}}:
 0.0