In [7]:
using JLD,JLD2,Knet, Distributions 
using Base.Iterators: flatten
include("types.jl")
include("pre_processing.jl")
include("encoder_utils.jl")

┌ Info: Precompiling Distributions [31c24e10-a181-5473-b8eb-7969acd0382f]
└ @ Base loading.jl:1186


fillvecs! (generic function with 1 method)

In [2]:
d = JLD.load("pretrained_model.jld2")
v = create_vocab(d)
corpus = load_conllu("tr_imst-ud-train.conllu",v)
wmodel = makewmodel(d)
fillvecs!(wmodel, corpus, v)

┌ Warning: `getval` is deprecated, use `value` instead.
│   caller = #lmloss#18(::Array{Float64,1}, ::Function, ::Array{Array{Float32,2},1}, ::Array{Array{Int64,1},1}, ::Array{Array{Float32,1},1}, ::Array{Any,1}, ::Array{Any,1}) at encoder_utils.jl:59
└ @ Main /home/ilayda/GBDP/encoder_utils.jl:59


In [3]:
ev = extend_vocab!(v, corpus)

ExtendedVocab(Dict("Abr"=>26,"PCNom"=>18,"Dup"=>27,"PCIns"=>30,"Since"=>32,"Postp"=>31,"Interj"=>24,"Ques"=>14,"Demons"=>5,"NAdj"=>11…), Dict("VerbForm=Vnoun"=>43,"Person=3"=>4,"Case=Acc"=>11,"Number=Sing"=>7,"Mood=Nec"=>54,"Aspect=Prog"=>27,"Person[psor]=3"=>13,"VerbForm=Conv"=>44,"Aspect=Hab"=>15,"Voice=CauPass"=>46…), Vocab(Dict('\x00\x00\x00\x42'=>37,'\x00\x00\x20\x1d'=>116,'\x00\x00\x00\x58'=>87,'\x00\x00\x20\x44'=>110,'\x00\x00\x00\x56'=>59,'\x00\x00\x00\xd7'=>107,'\x00\x00\x00\x48'=>29,'\x00\x00\x00\x75'=>5,'\x00\x00\x00\x50'=>11,'\x00\x00\x00\x7a'=>61…), Dict("çıkaramayacaklarını"=>7805,"apartmanın"=>13565,"Güreş"=>2733,"karıştı"=>1790,"ikibin'de"=>7225,"formülü"=>4676,"ANAP'ı"=>4506,"ihmal"=>5116,"Virgülden"=>9483,"il"=>6725…), Dict("null"=>8668,"Secure"=>7932,"Puppy"=>9040,"progression"=>11757,"gathered"=>6954,"Core"=>3600,"lovers"=>8832,"underground"=>9093,"backup"=>5047,"caught"=>2501…), "<s>", "</s>", "<unk>", '\x00\x00\x00\x12', '\x00\x00\x00\x13', '\x00\x00\x00\x11', Dic

In [9]:
mutable struct FeatureSource
    upostags::Array{Array(Float64)}
    xpostags::Array{Array(Float64)}
    feats::Array{Array(Float64)}
end

MethodError: MethodError: no method matching Array(::Type{Float64})
Closest candidates are:
  Array(!Matched::LinearAlgebra.SymTridiagonal) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/tridiag.jl:111
  Array(!Matched::LinearAlgebra.Tridiagonal) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/tridiag.jl:489
  Array(!Matched::LinearAlgebra.AbstractTriangular) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/triangular.jl:106
  ...

In [ ]:
function createcolvecs!(Extended_vocab,corpus)
    xpostags = []
    upostags = []
    feats = []
    
    for sent in corpus
        for i in 1:length(sent)
            push!(sent.cavec, vcat(sent.wvec[i], sent.fvec[i], sent.bvec[i], sent.postag[i], sent.xpostag[i], sent.feats[i]))
        end
    end
end

In [10]:
dist = Normal()

Normal{Float64}(μ=0.0, σ=1.0)

In [11]:
a = rand(dist,(2,3))

2×3 Array{Float64,2}:
 -0.102956  -0.259788  -0.855981
  0.115339   0.122011   1.64104 

In [15]:
a = rand(dist,(32, length(keys(ev.xpostags))))

32×34 Array{Float64,2}:
  2.64738    0.356065   -0.522548   …   0.737931    1.50616     0.631333 
 -1.05943   -0.401209    1.01543        0.418382   -0.703719    0.162307 
 -1.02163    0.7962     -0.785027       0.807925   -0.414833    0.855289 
 -1.01973   -0.366373    0.591055      -0.555129   -1.15228    -0.23496  
 -1.00136    0.804621    0.0312298     -0.569443   -0.103049   -1.00356  
  0.242632  -0.881878   -1.35345    …   0.492098   -0.762552   -0.0121825
 -1.75792   -0.486942    0.59028        1.36616    -0.0716801  -0.773718 
 -1.2243     1.37588     0.816867       0.157569    0.600204    0.119614 
 -0.746943  -1.03267    -0.930638       0.0182059  -0.253404    0.46443  
  0.4705    -0.0229171   1.33537        0.803932   -1.41742     0.730859 
  0.409764  -2.79941     0.69334    …   0.681647   -0.899705   -2.08417  
  2.28966    0.453024    0.186135       0.292267   -3.71119     0.478341 
 -0.775112  -1.19674     0.11783        0.0893091   0.01477    -0.26964  
  ⋮           

In [14]:
length(keys(ev.xpostags))

34

In [16]:
ev.upostags

ErrorException: type ExtendedVocab has no field upostags

In [17]:
ev.v

ErrorException: type ExtendedVocab has no field v

In [18]:
ev.vocab

Vocab(Dict('\x00\x00\x00\x42'=>37,'\x00\x00\x20\x1d'=>116,'\x00\x00\x00\x58'=>87,'\x00\x00\x20\x44'=>110,'\x00\x00\x00\x56'=>59,'\x00\x00\x00\xd7'=>107,'\x00\x00\x00\x48'=>29,'\x00\x00\x00\x75'=>5,'\x00\x00\x00\x50'=>11,'\x00\x00\x00\x7a'=>61…), Dict("çıkaramayacaklarını"=>7805,"apartmanın"=>13565,"Güreş"=>2733,"karıştı"=>1790,"ikibin'de"=>7225,"formülü"=>4676,"ANAP'ı"=>4506,"ihmal"=>5116,"Virgülden"=>9483,"il"=>6725…), Dict("null"=>8668,"Secure"=>7932,"Puppy"=>9040,"progression"=>11757,"gathered"=>6954,"Core"=>3600,"lovers"=>8832,"underground"=>9093,"backup"=>5047,"caught"=>2501…), "<s>", "</s>", "<unk>", '\x00\x00\x00\x12', '\x00\x00\x00\x13', '\x00\x00\x00\x11', Dict("NUM"=>0x09,"DET"=>0x06,"X"=>0x11,"VERB"=>0x10,"PROPN"=>0x0c,"ADV"=>0x03,"ADJ"=>0x01,"AUX"=>0x04,"PUNCT"=>0x0d,"PRON"=>0x0b…), Dict("reparandum"=>0x23,"root"=>0x01,"vocative"=>0x24,"csubj"=>0x0f,"advmod"=>0x04,"expl"=>0x14,"iobj"=>0x18,"mark"=>0x1a,"advcl"=>0x03,"nmod"=>0x1b…))

In [20]:
ev.feats

Dict{String,Int64} with 62 entries:
  "VerbForm=Vnoun"    => 43
  "Person=3"          => 4
  "Case=Acc"          => 11
  "Number=Sing"       => 7
  "Mood=Nec"          => 54
  "Aspect=Prog"       => 27
  "Person[psor]=3"    => 13
  "VerbForm=Conv"     => 44
  "Aspect=Hab"        => 15
  "Voice=CauPass"     => 46
  "Mood=Cnd"          => 6
  "Polite=Form"       => 53
  "Mood=CndPot"       => 55
  "Number=Plur"       => 3
  "Aspect=Perf"       => 5
  "Number[psor]=Sing" => 12
  "Tense=Fut,Past"    => 48
  "Case=Gen"          => 9
  "NumType=Ord"       => 52
  "Tense=Pres"        => 8
  "Case=Abl"          => 29
  "Person[psor]=1"    => 20
  "VerbForm=Part"     => 31
  "Abbr=Yes"          => 49
  "Mood=Gen"          => 42
  ⋮                   => ⋮

In [21]:
a = zeros(23,2)

23×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [22]:
a .+= 1

23×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0